### try/catch
  try/catch/finally语句是JavaScript的异常处理机制。try从句定义了需要处理的异常所在的代码块，当try块代码出现异常时，就会调用catch块中的的代码。不论try块中的代码是否出现异常，finally块内的代码必定执行。

```
try {
    undefined(); // 用非法的操作强制产生一个异常！
}
catch (e) {
    e = 1
    console.log(e); // 1
}

console.log(e); // ReferenceError: e is not found
```


catch块会创建一个新的变量对象，将变量对象添加到作用域链顶端。
换而言之，catch块中定义的变量拥有块级作用域。上面代码显示的变量e只存在于catch块，在外部引用会报错。
catch块的块级作用域性质可以shim ES6中新添加的let和const等块级作用域。

注意：
`在IE8以及之前的版本中，catch块捕获的变量对象会添加到所在函数的变量对象上，如果不被函数包裹，则会添加到全局对象上。`